<?php

return [
    'company_name' => env('TELESALES_COMPANY_NAME', 'HỆ THỐNG VẬN HÀNH TELESALE'),

    'modules' => [
        [
            'key' => 'organization',
            'number' => 1,
            'label' => 'Quản trị đơn vị',
            'icon' => 'icon-setting',
            'roles' => ['admin'],
            'children' => [
                ['label' => 'Tổng quan đơn vị', 'route' => 'admin.dashboard.index'],
                ['label' => 'Nhân sự', 'route' => 'admin.settings.users.index'],
                ['label' => 'Nhóm làm việc', 'route' => 'admin.settings.groups.index'],
                ['label' => 'Vai trò & phân quyền', 'route' => 'admin.settings.roles.index'],
                ['label' => 'Cấu hình hệ thống', 'route' => 'admin.configuration.index'],
            ],
        ],
        [
            'key' => 'marketing',
            'number' => 2,
            'label' => 'Marketing',
            'icon' => 'icon-stats-up',
            'roles' => ['admin', 'marketing'],
            'children' => [
                [
                    'label' => 'Marketing dashboard',
                    'route' => 'admin.telesales.rankings.index',
                    'params' => ['perspective' => 'marketing'],
                ],
                ['label' => 'Bảng xếp hạng', 'route' => 'admin.telesales.rankings.index'],
                ['label' => 'Hồ sơ data đã nhập', 'route' => 'admin.telesales.created-leads.index'],
                [
                    'label' => 'Kết nối landing - website',
                    'route' => 'admin.telesales.source-connections.index',
                ],
                [
                    'label' => 'Kết nối Facebook/API',
                    'route' => 'admin.telesales.source-connections.index',
                ],
                ['label' => 'Tiện ích Marketing', 'status' => 'planned'],
                [
                    'label' => 'Báo cáo',
                    'route' => 'admin.telesales.rankings.index',
                    'params' => ['perspective' => 'marketing'],
                ],
                ['label' => 'Marketing Leader', 'status' => 'planned'],
                ['label' => 'Thương mại điện tử', 'status' => 'planned'],
            ],
        ],
        [
            'key' => 'customer-360',
            'number' => 3,
            'label' => 'Khách hàng 360',
            'icon' => 'icon-contact',
            'roles' => ['admin', 'marketing', 'sale', 'leader'],
            'children' => [
                [
                    'label' => 'Hồ sơ khách hàng',
                    'route' => 'admin.contacts.persons.index',
                    'routes' => [
                        'marketing' => 'admin.telesales.created-leads.index',
                        'sale' => 'admin.telesales.created-leads.index',
                        'leader' => 'admin.telesales.created-leads.index',
                    ],
                ],
                [
                    'label' => 'Lịch sử chăm sóc',
                    'route' => 'admin.activities.index',
                    'routes' => [
                        'marketing' => 'admin.telesales.created-leads.index',
                        'sale' => 'admin.telesales.created-leads.index',
                        'leader' => 'admin.telesales.created-leads.index',
                    ],
                ],
                [
                    'label' => 'Doanh nghiệp',
                    'route' => 'admin.contacts.organizations.index',
                    'roles' => ['admin'],
                ],
                ['label' => 'Phân nhóm khách hàng', 'status' => 'planned'],
            ],
        ],
        [
            'key' => 'telesale',
            'number' => 4,
            'label' => 'Telesale',
            'icon' => 'icon-call',
            'roles' => ['admin', 'sale', 'leader'],
            'children' => [
                ['label' => 'Tác nghiệp telesale', 'route' => 'admin.telesales.created-leads.index'],
                ['label' => 'Hồ sơ khách hàng', 'route' => 'admin.telesales.created-leads.index'],
                ['label' => 'Bảng xếp hạng', 'route' => 'admin.telesales.rankings.index'],
                ['label' => 'Đơn telesale', 'route' => 'admin.telesales.orders.index'],
                ['label' => 'Kho số thả nổi', 'status' => 'planned'],
                ['label' => 'Báo cáo', 'route' => 'admin.telesales.rankings.index'],
                ['label' => 'Báo cáo Leader', 'status' => 'planned', 'roles' => ['admin', 'leader']],
                [
                    'label' => 'Cấu hình phân data',
                    'route' => 'admin.telesales.groups.index',
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'key' => 'warehouse',
            'number' => 5,
            'label' => 'Kho',
            'icon' => 'icon-tag',
            'roles' => ['admin'],
            'children' => [
                ['label' => 'Đăng đơn', 'route' => 'admin.telesales.orders.index'],
                ['label' => 'Quản lý kho', 'route' => 'admin.settings.warehouses.index'],
                ['label' => 'Sản phẩm & tồn kho', 'route' => 'admin.products.index'],
                ['label' => 'Nhập, xuất kho', 'status' => 'planned'],
                ['label' => 'Quản lý biên bản', 'status' => 'planned'],
                ['label' => 'Báo cáo kho', 'status' => 'planned'],
                ['label' => 'Thương mại điện tử', 'status' => 'planned'],
                ['label' => 'Cấu hình care đơn', 'status' => 'planned'],
            ],
        ],
        [
            'key' => 'accounting',
            'number' => 6,
            'label' => 'Kế toán',
            'icon' => 'icon-dollar',
            'roles' => ['admin'],
            'children' => [
                ['label' => 'Đối soát đơn', 'route' => 'admin.telesales.orders.index'],
                ['label' => 'Quản lý chi phí đơn vị', 'status' => 'planned'],
                ['label' => 'Báo cáo', 'route' => 'admin.telesales.rankings.index'],
                ['label' => 'Danh sách xử lý HĐĐT', 'status' => 'planned'],
                ['label' => 'Báo giá', 'route' => 'admin.quotes.index'],
            ],
        ],
        [
            'key' => 'ceo',
            'number' => 7,
            'label' => 'CEO',
            'icon' => 'icon-configuration',
            'roles' => ['admin'],
            'children' => [
                ['label' => 'Dashboard điều hành', 'route' => 'admin.dashboard.index'],
                ['label' => 'Bảng xếp hạng', 'route' => 'admin.telesales.rankings.index'],
                ['label' => 'Khách hàng 360', 'route' => 'admin.contacts.persons.index'],
                ['label' => 'Hiệu suất phòng ban', 'status' => 'planned'],
            ],
        ],
        [
            'key' => 'reports',
            'number' => 8,
            'label' => 'Báo cáo thống kê',
            'icon' => 'icon-dashboard',
            'roles' => ['admin', 'marketing', 'sale', 'leader'],
            'children' => [
                [
                    'label' => 'Marketing',
                    'route' => 'admin.telesales.rankings.index',
                    'params' => ['perspective' => 'marketing'],
                    'roles' => ['admin', 'marketing'],
                ],
                [
                    'label' => 'Sale',
                    'route' => 'admin.telesales.rankings.index',
                    'params' => ['perspective' => 'sale'],
                    'roles' => ['admin', 'sale', 'leader'],
                ],
                ['label' => 'Kho', 'status' => 'planned', 'roles' => ['admin']],
                ['label' => 'Kế toán', 'status' => 'planned', 'roles' => ['admin']],
                ['label' => 'Quản trị', 'status' => 'planned', 'roles' => ['admin']],
                ['label' => 'Số liệu nâng cao', 'status' => 'planned', 'roles' => ['admin']],
                ['label' => 'Khách hàng 360', 'status' => 'planned'],
            ],
        ],
        [
            'key' => 'paid-services',
            'number' => 9,
            'label' => 'Dịch vụ trả phí',
            'icon' => 'icon-percentage',
            'roles' => ['admin'],
            'children' => [
                ['label' => 'Kho ứng dụng', 'status' => 'planned'],
            ],
        ],
    ],
];
