<x-admin::layouts>
    <x-slot:title>Tác nghiệp chăm sóc khách hàng cũ</x-slot>
    <div class="flex flex-col gap-4">
        <div class="rounded-xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h1 class="text-xl font-bold dark:text-white">Tác nghiệp chăm sóc khách hàng cũ</h1><p class="mt-1 text-sm text-gray-500">Data được phân riêng cho bộ phận CSKH, không trộn với data Sale mới.</p></div>
        <form method="GET" class="flex flex-wrap gap-3 rounded-xl border bg-white p-4 dark:border-gray-800 dark:bg-gray-900"><input name="search" value="{{ request('search') }}" placeholder="Tên hoặc số điện thoại" class="min-w-72 rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950"><select name="status" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950"><option value="">Tất cả trạng thái</option>@foreach (config('telesales.customer_care_statuses') as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select><button class="primary-button">Tìm kiếm</button><a href="{{ route('admin.telesales.customer-care.cases.index') }}" class="secondary-button">Xóa lọc</a></form>
        <div class="overflow-x-auto rounded-xl border bg-white dark:border-gray-800 dark:bg-gray-900"><table class="w-full min-w-[1300px] text-sm dark:text-white"><thead class="bg-[#3677d8] text-white"><tr><th class="p-3">Khách hàng</th><th class="p-3">Marketing lấy số</th><th class="p-3">Sale đã bán</th><th class="p-3">CSKH phụ trách</th><th class="p-3">Chiến dịch</th><th class="p-3">Nội dung</th><th class="p-3">Trạng thái</th><th class="p-3">Hẹn gọi</th><th class="p-3">Thao tác</th></tr></thead><tbody>
            @forelse ($cases as $case)<tr class="border-t align-top dark:border-gray-800"><td class="p-3"><strong>{{ $case->person?->name }}</strong><div><a href="tel:{{ $case->person?->normalized_phone }}" class="text-blue-600">{{ $case->person?->normalized_phone }}</a></div><span class="mt-1 inline-flex rounded-full bg-orange-100 px-2 py-0.5 text-xs font-bold text-orange-700">Khách hàng cũ</span></td><td class="p-3">{{ $case->marketingOwner?->name ?: 'Chưa xác định' }}</td><td class="p-3">{{ $case->salesOwner?->name ?: 'Chưa xác định' }}</td><td class="p-3">{{ $case->careOwner?->name ?: 'Chưa phân bổ' }}</td><td class="p-3">{{ $case->campaign?->name ?: ($case->case_type === 'post_sale' ? 'Sau bán' : 'Data quay lại') }}</td><td class="max-w-sm p-3">{{ $case->message ?: $case->product_interest }}</td><td class="p-3">{{ config('telesales.customer_care_statuses.'.$case->status, $case->status) }}</td><td class="p-3">{{ $case->callback_at?->format('d/m/Y H:i') ?: '—' }}</td><td class="p-3"><a href="{{ route('admin.telesales.customer-care.cases.show', $case->id) }}" class="primary-button inline-flex">Tác nghiệp</a></td></tr>@empty<tr><td colspan="9" class="p-8 text-center text-gray-500">Chưa có ca chăm sóc được giao.</td></tr>@endforelse
            </tbody></table></div>{{ $cases->links() }}
    </div>
</x-admin::layouts>
