<x-admin::layouts>
    <x-slot:title>Chăm sóc {{ $careCase->person?->name }}</x-slot>
    @php($phone = $careCase->person?->normalized_phone ?: data_get($careCase->person?->contact_numbers, '0.value'))
    <div class="mx-auto flex max-w-6xl flex-col gap-4">
        <div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><div><div class="mb-2 inline-flex rounded-full bg-orange-100 px-3 py-1 text-sm font-bold text-orange-700">Khách hàng cũ</div><h1 class="text-2xl font-bold dark:text-white">{{ $careCase->person?->name }}</h1><p class="mt-1 text-sm text-gray-500">Marketing: {{ $careCase->marketingOwner?->name ?: 'Chưa xác định' }} · Sale cũ: {{ $careCase->salesOwner?->name ?: 'Chưa xác định' }} · CSKH: {{ $careCase->careOwner?->name ?: 'Chưa phân' }}</p></div><a href="tel:{{ $phone }}" class="primary-button">Gọi {{ $phone }}</a></div>
        <div class="grid gap-4 lg:grid-cols-2">
            <div class="rounded-xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="font-bold dark:text-white">Thông tin cần triển khai</h2><div class="mt-3 grid gap-2 text-sm dark:text-white"><p><strong>Chiến dịch:</strong> {{ $careCase->campaign?->name ?: 'Chăm sóc sau bán' }}</p><p><strong>Sản phẩm:</strong> {{ $careCase->product_interest ?: 'Chưa xác định' }}</p><p><strong>Nội dung:</strong> {{ $careCase->message ?: 'Không có' }}</p><p><strong>Data về:</strong> {{ $careCase->data_received_at?->format('d/m/Y H:i') }}</p></div></div>
            <form method="POST" action="{{ route('admin.telesales.customer-care.cases.outcome', $careCase->id) }}" class="rounded-xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900">@csrf<h2 class="font-bold dark:text-white">Kết quả chăm sóc</h2><div class="mt-3 grid gap-3"><select name="result" required class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950">@foreach (config('telesales.call_results') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><textarea name="note" rows="3" placeholder="Ghi chú nội bộ CSKH" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950"></textarea><textarea name="marketing_feedback" rows="2" placeholder="Phản hồi cho Marketing" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950"></textarea><input type="datetime-local" name="callback_at" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950"><button class="primary-button">Lưu kết quả</button></div></form>
        </div>
        <form method="POST" action="{{ route('admin.telesales.customer-care.cases.order', $careCase->id) }}" class="grid gap-3 rounded-xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900 md:grid-cols-3">@csrf<h2 class="font-bold dark:text-white md:col-span-3">Tạo đơn mua lại / upsale</h2><select name="product_id" required class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950"><option value="">Chọn sản phẩm</option>@foreach ($products as $product)<option value="{{ $product->id }}">{{ $product->name ?: $product->sku }}</option>@endforeach</select><input type="number" name="quantity" min="1" value="1" required class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950" placeholder="Số lượng"><input type="number" name="unit_price" min="0" required class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950" placeholder="Đơn giá"><input type="number" name="discount_amount" min="0" value="0" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950" placeholder="Chiết khấu"><input type="number" name="shipping_fee" min="0" value="0" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950" placeholder="Phí vận chuyển"><input type="number" name="deposit_amount" min="0" value="0" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950" placeholder="Đặt cọc"><select name="status" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950">@foreach (config('telesales.order_statuses') as $value => $label)<option value="{{ $value }}" @selected($value === 'confirmed')>{{ $label }}</option>@endforeach</select><select name="delivery_status" class="rounded-md border px-3 py-2 dark:border-gray-700 dark:bg-gray-950">@foreach (config('telesales.delivery_statuses') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><button class="primary-button">Tạo đơn mua lại</button></form>
        <div class="rounded-xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 class="mb-3 font-bold dark:text-white">Lịch sử chăm sóc</h2><div class="grid gap-2">@forelse ($careCase->histories->sortByDesc('id') as $history)<div class="rounded-lg border p-3 text-sm dark:border-gray-800 dark:text-white"><div class="flex justify-between gap-2"><strong>{{ config('telesales.call_results.'.$history->result, $history->result) }}</strong><span>{{ $history->created_at->format('d/m/Y H:i') }} · {{ $history->user?->name }}</span></div>@if ($history->note)<p class="mt-1">{{ $history->note }}</p>@endif @if ($history->marketing_feedback)<p class="mt-2 text-blue-600">Phản hồi Marketing: {{ $history->marketing_feedback }}</p>@endif</div>@empty<p class="text-sm text-gray-500">Chưa có lịch sử.</p>@endforelse</div></div>
    </div>
</x-admin::layouts>
